services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\BootstrapBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaBootstrapBundle.php'
